/*
Deployment script for Rat.Database

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "RatDb"
:setvar DefaultFilePrefix "RatDb"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF;
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
/* Please run the below section of statements against 'master' database. */
PRINT N'Creating database $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)] COLLATE SQL_Latin1_General_CP1_CI_AS
GO
DECLARE  @job_state INT = 0;
DECLARE  @index INT = 0;
DECLARE @EscapedDBNameLiteral sysname = N'$(DatabaseName)'
WAITFOR DELAY '00:00:30';
WHILE (@index < 60)
BEGIN
	SET @job_state = ISNULL( (SELECT SUM (result)  FROM (
		SELECT TOP 1 [state] AS result
		FROM sys.dm_operation_status WHERE resource_type = 0
		AND operation = 'CREATE DATABASE' AND major_resource_id = @EscapedDBNameLiteral AND [state] = 2
		ORDER BY start_time DESC
		) r), -1);

	SET @index = @index + 1;

	IF @job_state = 0 /* pending */ OR @job_state = 1 /* in progress */ OR @job_state = -1 /* job not found */ OR (SELECT [state] FROM sys.databases WHERE name = @EscapedDBNameLiteral) <> 0
		WAITFOR DELAY '00:00:30';
	ELSE
    	BREAK;
END
GO
/* Please run the below section of statements against the database name that the above [$(DatabaseName)] variable is assigned to. */
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                DATE_CORRELATION_OPTIMIZATION OFF
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100)
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE = OFF
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF EXISTS (SELECT 1
           FROM   [sys].[databases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET TEMPORAL_HISTORY_RETENTION ON
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating Table [dbo].[ConfigurationType]...';


GO
CREATE TABLE [dbo].[ConfigurationType] (
    [Id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_ConfigurationType_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ProjectType]...';


GO
CREATE TABLE [dbo].[ProjectType] (
    [Id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_ProjectType_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([Name] ASC)
);


GO
PRINT N'Creating Table [dbo].[Project]...';


GO
CREATE TABLE [dbo].[Project] (
    [Id]            INT                IDENTITY (1, 1) NOT NULL,
    [Name]          NVARCHAR (128)     NOT NULL,
    [ProjectTypeId] INT                NOT NULL,
    [Created]       DATETIMEOFFSET (7) NOT NULL,
    [Modified]      DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_Project_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConfigurationRoot]...';


GO
CREATE TABLE [dbo].[ConfigurationRoot] (
    [Id]                  INT                IDENTITY (1, 1) NOT NULL,
    [Name]                NVARCHAR (128)     NOT NULL,
    [ConfigurationTypeId] INT                NOT NULL,
    [Created]             DATETIMEOFFSET (7) NOT NULL,
    [Modified]            DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_ConfigurationRoot_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConfigurationEntry]...';


GO
CREATE TABLE [dbo].[ConfigurationEntry] (
    [Id]                  INT                IDENTITY (1, 1) NOT NULL,
    [ConfigurationRootId] INT                NOT NULL,
    [Key]                 NVARCHAR (128)     NOT NULL,
    [Value]               NVARCHAR (2048)    NOT NULL,
    [Disabled]            BIT                NOT NULL,
    [Created]             DATETIMEOFFSET (7) NOT NULL,
    [Modified]            DATETIMEOFFSET (7) NOT NULL,
    CONSTRAINT [PK_ConfigurationEntry_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[MemberProject]...';


GO
CREATE TABLE [dbo].[MemberProject] (
    [MemberId]  INT NOT NULL,
    [ProjectId] INT NOT NULL,
    CONSTRAINT [PK_MemberProject_Id] PRIMARY KEY CLUSTERED ([MemberId] ASC, [ProjectId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Member]...';


GO
CREATE TABLE [dbo].[Member] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [AuthProviderId] NVARCHAR (128) NOT NULL,
    CONSTRAINT [PK_User_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ_AuthProviderId] UNIQUE NONCLUSTERED ([AuthProviderId] ASC)
);


GO
PRINT N'Creating Index [dbo].[Member].[IX_User_AuthProviderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_User_AuthProviderId]
    ON [dbo].[Member]([AuthProviderId] ASC);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Project]...';


GO
ALTER TABLE [dbo].[Project]
    ADD DEFAULT GETUTCDATE() FOR [Created];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Project]...';


GO
ALTER TABLE [dbo].[Project]
    ADD DEFAULT GETUTCDATE() FOR [Modified];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ConfigurationRoot]...';


GO
ALTER TABLE [dbo].[ConfigurationRoot]
    ADD DEFAULT GETUTCDATE() FOR [Created];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ConfigurationRoot]...';


GO
ALTER TABLE [dbo].[ConfigurationRoot]
    ADD DEFAULT GETUTCDATE() FOR [Modified];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ConfigurationEntry]...';


GO
ALTER TABLE [dbo].[ConfigurationEntry]
    ADD DEFAULT 0 FOR [Disabled];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ConfigurationEntry]...';


GO
ALTER TABLE [dbo].[ConfigurationEntry]
    ADD DEFAULT GETUTCDATE() FOR [Created];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ConfigurationEntry]...';


GO
ALTER TABLE [dbo].[ConfigurationEntry]
    ADD DEFAULT GETUTCDATE() FOR [Modified];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Project_ProjectType]...';


GO
ALTER TABLE [dbo].[Project]
    ADD CONSTRAINT [FK_Project_ProjectType] FOREIGN KEY ([ProjectTypeId]) REFERENCES [dbo].[ProjectType] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConfigurationRoot_ConfigurationType]...';


GO
ALTER TABLE [dbo].[ConfigurationRoot]
    ADD CONSTRAINT [FK_ConfigurationRoot_ConfigurationType] FOREIGN KEY ([ConfigurationTypeId]) REFERENCES [dbo].[ConfigurationType] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConfigurationEntry_ConfigurationRoot]...';


GO
ALTER TABLE [dbo].[ConfigurationEntry]
    ADD CONSTRAINT [FK_ConfigurationEntry_ConfigurationRoot] FOREIGN KEY ([ConfigurationRootId]) REFERENCES [dbo].[ConfigurationRoot] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MemberProject_User]...';


GO
ALTER TABLE [dbo].[MemberProject]
    ADD CONSTRAINT [FK_MemberProject_User] FOREIGN KEY ([MemberId]) REFERENCES [dbo].[Member] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_MemberProject_Project]...';


GO
ALTER TABLE [dbo].[MemberProject]
    ADD CONSTRAINT [FK_MemberProject_Project] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Project] ([Id]);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'a8c1facd-de0a-4375-a104-34489e6d7318')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('a8c1facd-de0a-4375-a104-34489e6d7318')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd7ba0951-1cff-47b1-b76e-4deed6ad3850')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d7ba0951-1cff-47b1-b76e-4deed6ad3850')

GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
