name: CI

on:
  push:
    branches: [ branch0 ]
  pull_request:
    branches: [ branch0 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: branch0
      DEFAULT_DOCKER_IMAGE_TAG: latest
      DOCKER_REPOSITORY: rat

    services:
      #sqlserver:
      #  image: mcr.microsoft.com/mssql/server:2019-latest
      #  env:
      #    ACCEPT_EULA: Y
      #    SA_PASSWORD: Password1!
      #  ports:
      #    - 1433:1433

      postgres:
        image: postgres
        env:
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: Password1!
          POSTGRES_DB: RatDb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup .NET Core SDK
        id: install-dotnet-50x
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Checkout
        id: git-checkhot
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup CodeQL
        id: codeql-setup
        uses: github/codeql-action/init@v1
        with:
          languages: 'csharp'

      - name: Restore nuget packages
        id: dotnet-restore
        run: dotnet restore ./src/Rat.sln

      - name: Build
        id: dotnet-build
        run: dotnet build ./src/Rat.sln --configuration Release --no-restore

      - name: Test
        id: dotnet-test
        env:
          DATABASE_ENGINE: postgres
        run: dotnet test ./src/Rat.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --settings ./src/Rat.Api.Test/runsettings.xml

      - name: Publish
        id: dotnet-publish
        run: dotnet publish ./src/Rat.Api/Rat.Api.csproj -o ./published

      - name: Upload publish result
        uses: actions/upload-artifact@v2
        with:
          name: published
          path: |
            published

      - name: Setup Docker QEMU
        id: docker-qemu
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: docker-buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        id: docker-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get branch Name
        id: get-branch-name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Set default docker image tag
        id: set-default-docker-image-tag
        if: env.BRANCH != env.DEFAULT_BRANCH
        run: echo "DEFAULT_DOCKER_IMAGE_TAG=$(echo $BRANCH)" >> $GITHUB_ENV

      - name: Set unique docker image tag
        id: set-unique-docker-image-tag
        run: echo "DOCKER_TAG=$(echo $GITHUB_RUN_ID)" >> $GITHUB_ENV

      - name: Docker build
        id: docker-build
        uses: docker/build-push-action@v2
        env:
          PUBLISH_RESULT_PATH: /published
        with:
          context: .
          file: ./src/Rat.Api/Dockerfile
          build-args: PUBLISH_RESULT_PATH=published
          push: true
          tags: |
            throwifnull/rat:${{ env.DEFAULT_DOCKER_IMAGE_TAG }}
            throwifnull/rat:${{ env.DOCKER_TAG }}

      - name: 'Deploy container to Azure'
        id: azure-deployContainer
        uses: azure/webapps-deploy@v2
        with:
          app-name: rattus
          publish-profile: ${{ secrets.RAT_AZURE_PUBLISH_PROFILE }}
          images: 'docker.io/throwifnull/rat:${{ env.DOCKER_TAG }}'

      - uses: azure/login@v1
        id: azure-loging
        with:
          creds: '${{ secrets.RATCAT_AZURE_CREDENTIALS }}'

      - uses: azure/appservice-settings@v1
        id: azure-deployAppSettings
        with:
          app-name: 'rattus'
          connection-strings-json: |
            [
              {
                "name": "RatDb",
                "value": "${{ secrets.RAT_DATABASE_CONNECTION_STRING }}",
                "type": "Custom",
                "slotSetting": false
              }
            ]
          app-settings-json: |
            [
              {
                "name": "ASPNETCORE_ENVIRONMENT",
                "value": "Production",
                "slotSetting": false
              },
              {
                "name": "DOCKER_REGISTRY_SERVER_URL",
                "value": "https://index.docker.io/v1",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_HEALTHCHECK_MAXPINGFAILURES",
                "value": "2",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
                "value": "7",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                "value": "false",
                "slotSetting": false
              }
            ]

      #- name: Run CodeQL Analysis
      #  id: codeql-run
      #  uses: github/codeql-action/analyze@v1

      #- name: Build Docker image
      #  id: docker-build-publish
      #  uses: elgohr/Publish-Docker-Github-Action@3.04
      #  with:
      #    name: throwifnull/${{ env.DOCKER_REPOSITORY }}
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    context: .
      #    dockerfile: ./Rat.Api/Dockerfile
      #    workdir: ./src
      #    tags: "${{ env.DOCKER_TAG }},${{env.DEFAULT_DOCKER_IMAGE_TAG}}"

      #- name: Print published docker image tags
      #  id: print-docker-image-tags
      #  run: |
      #    echo "Published Docker tags:"
      #    echo $DEFAULT_DOCKER_IMAGE_TAG
      #    echo $DOCKER_TAG
