name: Build docs
on:
  workflow_run:
    workflows: ["page-build-deployment"]
    types: [requested]

jobs:
  build:
    name: Build Rat API documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: git-checkhot
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build docs
      run: ./make.sh

    - name: Deploy to GitHub Pages
      # https://github.com/peaceiris/actions-gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'
