name: Build docs
on:
  push:
    branches: [ branch0 ]
    paths:
      - '.github/workflows/redoc.yml'
      - index.html
      - 'images/**'

jobs:
  build:
    name: Build Rat API documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: git-checkhot
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build index.html
      id: redoc-build
      shell: bash
      continue-on-error: true
      run: |
        echo "Getting started"

        npx redoc-cli build swagger.json && \
        mv redoc-static.html index.html && \
        echo "Changed name from redoc-static.html to index.html" && \
        sed -i '7 i \ \ <link rel="icon" type="image/x-icon" href="images/favicon.ico">' index.html && \
        echo -e "\nDone!"

    - name: Deploy to GitHub Pages
      # https://github.com/peaceiris/actions-gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'
